#!/usr/bin/env python3
import sys
import re

if len(sys.argv) != 3:
    print("Usage: make_table.py input.h output.h", file=sys.stderr)
    sys.exit(1)

input_file = sys.argv[1]
output_file = sys.argv[2]

defines = []
first = 0x7fffffff
last = 0

with open(input_file, 'r') as f:
    for line in f:
        if not line.startswith('#'):
            continue
        tokens = line[1:].split()
        if len(tokens) < 2 or tokens[0] != 'define' or tokens[1] == '_yy_defines_h_' or tokens[1] == 'YYSTYPE_IS_DECLARED':
            continue
        name = tokens[1]
        value = tokens[2]
        defines.append((name, value))

with open(output_file, 'w') as out:
    out.write("/*\n")
    out.write(" * This file is automatically generated; do not edit.\n")
    out.write(" */\n\n")
    out.write("#ifdef EFUN_TABLE\n")
    out.write("static void (*efun_table[])(int) = {\n")
    for name, _ in defines:
        out.write(f"\t{name.lower()},\n")
    out.write("};\n")
    out.write("#else /* EFUN_TABLE */\n")
    out.write(f"#define EFUN_FIRST    {defines[0][1]}\n")
    out.write(f"#define EFUN_LAST   {defines[-1][1]}\n")
    out.write("#endif /* EFUN_TABLE */\n")
